version: 2.1
executors:
  build_machine:
    machine:
      image: ubuntu-1604:202007-01
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6
  test:
    docker:
    - image: python:3.7-slim-buster

commands:
  install_yq:
    description: Install yq to get API version from swagger.yaml
    steps:
      - run:
          name: Install yq
          command: |
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod a+x /usr/local/bin/yq
  install_pytest:
    description: Install pytest for running tests
    steps:
      - run:
          name: Install pytest
          command: pip install pytest

jobs:
  run_tests:
    executor: test
    steps:
      - checkout
      - install_pytest
      - run:
          name: Run tests
          command: python -m pytest test/

  build_and_publish:
    executor: build_machine
    steps:
      - checkout
      - install_yq
      - run:
          name: Build Image
          command: |
            export CONTACT_API_VERSION=$(yq eval '.info.version' swagger.yaml)
            docker build -t contact_api:$CONTACT_API_VERSION .
      - run:
          name: Check Branch
          command: |
            if [ "$CIRCLE_BRANCH" != "master" ]; then
                circleci-agent step halt
            fi
      - run:
          name: Publish Image
          command: |
            export CONTACT_API_VERSION=$(yq eval '.info.version' swagger.yaml)
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
            docker tag contact_api:$CONTACT_API_VERSION $DOCKER_USERNAME/contact_api:$CONTACT_API_VERSION
            docker push $DOCKER_USERNAME/contact_api:$CONTACT_API_VERSION


workflows:
  version: 2
  build_and_publish:
    jobs:
      - run_tests
      - build_and_publish