version: 2.1
executors:
  build_machine:
    machine:
      image: ubuntu-1604:202007-01
    environment:
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6

commands:
  install_yq:
    description: Install yq
    steps:
      - run:
          name: Install yq
          command: |
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod a+x /usr/local/bin/yq

jobs:
  build_and_publish:
    executor: build_machine
    steps:
      - checkout
      - install_yq
      - run:
          name: Build Image
          command: |
            export CONTACT_API_VERSION=$(yq eval '.info.version' swagger.yaml)
            docker build -t contact_api:$CONTACT_API_VERSION .
      - run: |
          if [ "$CIRCLE_BRANCH" != "master" ]; then
              circleci-agent step halt
          fi
      - run:
          name: Publish Image
          command: |
            export CONTACT_API_VERSION=$(yq eval '.info.version' swagger.yaml)
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin
            docker tag contact_api:$CONTACT_API_VERSION jalgraves/contact_api:$CONTACT_API_VERSION
            docker push jalgraves/contact_api:$CONTACT_API_VERSION


workflows:
  version: 2
  build_and_publish:
    jobs:
      - build_and_publish