apiVersion: v2
name: contact-api
description: Contact API deployment
type: application
version: 0.1.4
appVersion: 0.1.13
sources:
- https://github.com/beantownpub/contact-api

dependencies:
  - name: postgres
    version: 0.1.4
    repository: https://beantownpub.github.io/helm/
    condition: database.enabled
    namespace: database
