appName: contact-api
global:
  env: dev
image:
  repository: jalgraves/contact-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

containerPort: 5012

ingress:
  enabled: false

db:
  dbName: contact
  host:
  port:

logLevel: INFO
database:
  enabled: false

regionCode: use2

aws_access_key_id:
aws_secret_access_key:
aws_default_region:
aws_secret_name:
email_recipient:
second_email_recipient:
slack_channel:
slack_user:
slack_webhook_url:
support_email_address:
support_phone_number:
slack_partys_channel:
slack_orders_channel:
slack_orders_webhook_url:
slack_partys_webhook_url:
test_email_recipient:
