appName: contact-api
global:
  env: dev
image:
  repository: jalgraves/contact_api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

containerPort: 5012

ingress:
  enabled: false

db:
  dbName: contact
  host: postgres.default.svc.cluster.local
  port: 5432

logLevel: INFO
database:
  enabled: false

regionCode: use2
