appName: contact-api
aws:
  regionCode: use1
externalSecrets:
  enabled: true
  keys:
    - API_PASSWORD
    - API_USERNAME
    - AWS_ACCESS_KEY_ID
    - AWS_DEFAULT_REGION
    - AWS_SECRET_ACCESS_KEY
    - LOG_LEVEL
    - PRIMARY_EMAIL_RECIPIENT
    - SECONDARY_EMAIL_RECIPIENT
    - SLACK_ORDERS_CHANNEL
    - SLACK_ORDERS_WEBHOOK_URL
    - SLACK_PARTYS_CHANNEL
    - SLACK_PARTYS_WEBHOOK_URL
    - SLACK_USER
    - SLACK_WEBHOOK_URL
    - SUPPORT_EMAIL_ADDRESS
    - SUPPORT_PHONE_NUMBER
    - TEST_EMAIL_RECIPIENT
nameOverride:
fullnameOverride:
global:
  env:
image:
  name:
  repository: jalgraves/contact-api
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

containerPort: 5012

ingress:
  enabled: false

db:
  dbName: contact
  host:
  port:

database:
  enabled: false

replicaCount: 1
resources:
  requests:
    cpu: 25m
    memory: 100Mi
  limits:
    memory: 350Mi

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""


