apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "contact-api.fullname" . }}
  labels:
    app: {{ include "contact-api.fullname" . }}
spec:
  progressDeadlineSeconds: 300
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ include "contact-api.fullname" . }}
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "contact-api.fullname" . }}
    spec:
      containers:
      - env:
        {{- range .Values.externalSecrets.keys }}
        - name: '{{ . }}'
          valueFrom:
            secretKeyRef:
              name: contact-api
              key: '{{ . }}'
        {{- end }}
        - name: CONTACT_API_VERSION
          value: "{{ .Values.image.tag | default .Chart.AppVersion }}"
      {{- if eq .Values.global.env "dev" }}
        image: "contact-api:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Never
      {{- else }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
      {{- end }}
        name: contact-api
        ports:
        - containerPort: {{ .Values.containerPort }}
          name: tcp-contact-api
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        resources: {{- toYaml .Values.resources | nindent 10 }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "contact-api.serviceAccountName" . }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
