{{- if eq .Values.global.env "dev" }}
apiVersion: v1
data:
  aws_default_region: {{ .Values.aws.region | b64enc }}
  aws_secret_name: {{ .Values.aws.secretName | b64enc }}
kind: Secret
metadata:
  name: contact-api-creds
type: Opaque
{{- end }}
